"""D* diagnostics for the `short` profile (plan §20.10). Deterministic.

Only the diagnostics genuinely computable now, without H/HV rendering
(visual density, on-screen text density) or a fitted voice corpus
(sentence rhythm vs the short profile): time to hook event, setup length,
and word count vs the advisory band. Hook STRENGTH itself is C4s's job
(a judgement call), not this module's -- this only measures the
structural timing/length signals plan §20.10 lists as bandable.
"""
from __future__ import annotations

from narration.models import SceneNarration
from planning.shorts_models import ShortPlan
from review.models import DiagnosticResult
from verification.diagnostics.compactness import check_sentence_density

# Raised 10.0 -> 13.0 (2026-09-15): `setup` genuinely grew a second job (Phase 20's
# per-micro_arc required beat -- a naive attempt, a stated contradiction, ... --
# narration/short_generator.py's own prompt) on top of its original "minimum context"
# job. Confirmed live: 4 of 5 real shorts measured 15-17.6s against the old 10s target,
# turning a diagnostic meant to flag genuine bloat into a near-constant RED for setup
# segments doing their job correctly.
#
# Raised again 13.0 -> 18.0 (2026-09-16): that first recalibration's own evidence base
# was "15-17.6s, observed once." A second live round measured 14.8/25.4/30.9/24.5s across
# 4 different micro_arcs -- the low end still clears the OLD 13.0 evidence range
# comfortably, so 18.0 (just above that range) stops flagging the normal, expected case
# while still correctly banding the genuine outliers (25-31s) AMBER/RED rather than
# treating everything past 19.5s alike. Also added an explicit conciseness instruction to
# short_generator.py's own prompt (the real content fix -- this recalibration is a
# measurement fix, not a content one). Still advisory only (never a hard gate, plan
# §20.4), so recalibrating it doesn't change what a short is allowed to ship -- only
# whether the signal stays a useful one.
SETUP_LENGTH_TARGET_SECONDS = 18.0


def check_time_to_hook(plan: ShortPlan) -> DiagnosticResult:
    """Structurally always GREEN -- HookEvent.starts_at_seconds is already
    hard-bounded to 0-3s at the model level (plan §20.4) -- reported here
    for visibility in review_summary.md, not because it can actually fail."""
    seconds = plan.hook.starts_at_seconds
    return DiagnosticResult(
        dimension="short.time_to_hook", band="GREEN", value=seconds, target="<=3s",
        evidence=f"hook event starts at {seconds:.1f}s",
    )


def check_setup_length(narration: list[SceneNarration]) -> DiagnosticResult:
    setup = next((s for s in narration if s.scene_id == "setup"), None)
    if setup is None:
        return DiagnosticResult(dimension="short.setup_length", band="AMBER", evidence="no 'setup' segment found")
    seconds = setup.est_seconds
    band = "GREEN" if seconds <= SETUP_LENGTH_TARGET_SECONDS else "AMBER" if seconds <= SETUP_LENGTH_TARGET_SECONDS * 1.5 else "RED"
    return DiagnosticResult(
        dimension="short.setup_length", band=band, value=round(seconds, 1),
        target=f"<={SETUP_LENGTH_TARGET_SECONDS:.0f}s",
        evidence=f"setup segment estimated at {seconds:.1f}s",
    )


def check_word_count_band(plan: ShortPlan, narration: list[SceneNarration]) -> DiagnosticResult:
    total_words = sum(len(s.text.split()) for scene in narration for s in scene.sentences)
    low, high = plan.narration.word_band
    if low <= total_words <= high:
        band = "GREEN"
    elif (low * 0.8) <= total_words <= (high * 1.2):
        band = "AMBER"
    else:
        band = "RED"
    return DiagnosticResult(
        dimension="short.word_count", band=band, value=total_words, target=f"{low}-{high} (advisory)",
        evidence=f"{total_words} words across {sum(len(s.sentences) for s in narration)} sentences",
    )


def check_visual_states_present(plan: ShortPlan) -> DiagnosticResult:
    """2026-09-16: confirmed live -- `plan.visual.states` was empty in 5 of 5 real
    shorts across a full run (likely every short ever generated by this pipeline).
    `html_synth/vertical_assembler.py::synthesize_short_html()` only draws a flow
    diagram on the mechanism screen when `states` is non-empty -- an empty list has
    been silently producing a plain-text-only short.html this whole time, with no
    signal anywhere that the diagram capability was never actually firing.
    Advisory only (AMBER, never a hard gate) -- a short with correct narration but no
    diagram still functions; this exists so the gap is visible, not blocking."""
    if plan.visual.states:
        return DiagnosticResult(
            dimension="short.visual_states", band="GREEN",
            evidence=f"{len(plan.visual.states)} visual state(s): {plan.visual.states}",
        )
    return DiagnosticResult(
        dimension="short.visual_states", band="AMBER",
        evidence="visual.states is empty -- the mechanism screen will render as plain text, no flow diagram",
    )


def check_bridge_cta_present(plan: ShortPlan) -> DiagnosticResult:
    """2026-09-16, found on review -- ONSCREEN/PLATFORM_LINK explicitly mean the bridge
    renders as on-screen text rather than being spoken (`narration/short_generator.py`'s
    own prompt), but nothing enforced that `bridge.cta_text` was actually filled in --
    an empty one means `html_synth/vertical_assembler.py` has nothing to render, so the
    short ships with the bridge withheld from narration AND never shown anywhere else.
    Advisory only (AMBER) -- not a hard gate, since `bridge.mode` itself is the model's
    own honest judgement call and NONE/SPOKEN never trigger this at all."""
    if plan.bridge.mode not in ("ONSCREEN", "PLATFORM_LINK"):
        return DiagnosticResult(dimension="short.bridge_cta", band="GREEN", evidence=f"bridge.mode={plan.bridge.mode}, no on-screen CTA needed")
    if plan.bridge.cta_text.strip():
        return DiagnosticResult(
            dimension="short.bridge_cta", band="GREEN", evidence=f"cta_text={plan.bridge.cta_text!r}",
        )
    return DiagnosticResult(
        dimension="short.bridge_cta", band="AMBER",
        evidence=f"bridge.mode={plan.bridge.mode} but cta_text is empty -- nothing will render on the payoff screen",
    )


def check_short_diagnostics(plan: ShortPlan, narration: list[SceneNarration]) -> list[DiagnosticResult]:
    """The full D* short diagnostics pass -- every diagnostic, one call."""
    return [
        check_time_to_hook(plan), check_setup_length(narration), check_word_count_band(plan, narration),
        check_visual_states_present(plan), check_bridge_cta_present(plan),
        # STORY_IMPROVEMENT_PLAN.md Phase 23 item 8: `check_sentence_density` is generic over
        # any list[SceneNarration], no long-form-specific assumption -- reused as-is, same
        # 50-word threshold, rather than inventing a shorts-scaled number with no live evidence
        # yet that the general threshold is wrong here (this project's own "don't build ahead
        # of evidence" discipline). If anything, a single sentence that long matters MORE in a
        # short given its own much smaller total word budget (a 50-word sentence can be half a
        # 90-second short's entire narration).
        check_sentence_density(narration),
    ]
